In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
x = data.drop(['Outcome'], axis =1 ).values
y = data['Outcome'].values

In [4]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [5]:
from tensorflow.keras.utils import to_categorical 
#this code is one hot encoding in dependent variable colummn into two different columns 

In [6]:
y = to_categorical(y)
y[:5]

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2 ,random_state=50)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(614, 8) (614, 2) (154, 8) (154, 2)


In [8]:
#creating neural network
from  tensorflow.keras.models import Sequential
from  tensorflow.keras.layers import Dense
#creating model
model = Sequential() #creating model

In [15]:
#adding neurons

model.add(Dense(512, activation = 'relu', input_dim = 8)) #adding input layer
model.add(Dense(228, activation = 'relu')) #adding hidden layer with 228 neurons
model.add(Dense(228, activation = 'relu'))#adding hidden layer with 228 neurons
model.add(Dense(50, activation = 'relu'))#adding hidden layer with 50 neurons
model.add(Dense(2, activation = 'softmax')) #adding output layer with 2 neurons because of softmax


In [16]:
model.compile(optimizer='adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

#in classification dataset, we always use categorica_crossentropy loss for calculating loss

In [17]:
model.fit(x_train,y_train ,epochs=200)

Epoch 1/200
20/20 [==============================] - 3s 8ms/step - loss: 0.3937 - accuracy: 0.8925
Epoch 2/200
20/20 [==============================] - 0s 10ms/step - loss: 0.2606 - accuracy: 0.9121
Epoch 3/200
20/20 [==============================] - 0s 9ms/step - loss: 0.3429 - accuracy: 0.8860
Epoch 4/200
20/20 [==============================] - 0s 8ms/step - loss: 0.2388 - accuracy: 0.9169
Epoch 5/200
20/20 [==============================] - 0s 10ms/step - loss: 0.1661 - accuracy: 0.9446
Epoch 6/200
20/20 [==============================] - 0s 11ms/step - loss: 0.1977 - accuracy: 0.9365
Epoch 7/200
20/20 [==============================] - 0s 12ms/step - loss: 0.3064 - accuracy: 0.8779
Epoch 8/200
20/20 [==============================] - 0s 12ms/step - loss: 0.3545 - accuracy: 0.8616
Epoch 9/200
20/20 [==============================] - 0s 8ms/step - loss: 0.2943 - accuracy: 0.8941
Epoch 10/200
20/20 [==============================] - 0s 8ms/step - loss: 0.2832 - accuracy: 0.9039
Epoc

20/20 [==============================] - 0s 14ms/step - loss: 0.1308 - accuracy: 0.9511
Epoch 83/200
20/20 [==============================] - 0s 9ms/step - loss: 0.1506 - accuracy: 0.9479
Epoch 84/200
20/20 [==============================] - 0s 8ms/step - loss: 0.0852 - accuracy: 0.9691
Epoch 85/200
20/20 [==============================] - 0s 8ms/step - loss: 0.0667 - accuracy: 0.9772
Epoch 86/200
20/20 [==============================] - 0s 10ms/step - loss: 0.1028 - accuracy: 0.9691
Epoch 87/200
20/20 [==============================] - 0s 10ms/step - loss: 0.0773 - accuracy: 0.9642
Epoch 88/200
20/20 [==============================] - 0s 10ms/step - loss: 0.0637 - accuracy: 0.9723
Epoch 89/200
20/20 [==============================] - 0s 10ms/step - loss: 0.0552 - accuracy: 0.9788
Epoch 90/200
20/20 [==============================] - 0s 14ms/step - loss: 0.0590 - accuracy: 0.9691
Epoch 91/200
20/20 [==============================] - 0s 16ms/step - loss: 0.0481 - accuracy: 0.9821
Epoch 

20/20 [==============================] - 0s 9ms/step - loss: 0.0959 - accuracy: 0.9642
Epoch 164/200
20/20 [==============================] - 0s 9ms/step - loss: 0.1321 - accuracy: 0.9544
Epoch 165/200
20/20 [==============================] - 0s 9ms/step - loss: 0.1005 - accuracy: 0.9658
Epoch 166/200
20/20 [==============================] - 0s 8ms/step - loss: 0.0942 - accuracy: 0.9658
Epoch 167/200
20/20 [==============================] - 0s 10ms/step - loss: 0.0906 - accuracy: 0.9723
Epoch 168/200
20/20 [==============================] - 0s 9ms/step - loss: 0.0962 - accuracy: 0.9739
Epoch 169/200
20/20 [==============================] - 0s 10ms/step - loss: 0.0991 - accuracy: 0.9707
Epoch 170/200
20/20 [==============================] - 0s 9ms/step - loss: 0.2044 - accuracy: 0.9235
Epoch 171/200
20/20 [==============================] - 0s 10ms/step - loss: 0.1298 - accuracy: 0.9544
Epoch 172/200
20/20 [==============================] - 0s 9ms/step - loss: 0.0911 - accuracy: 0.9691
E

Now we got our training accuracy as 97%. Now we will find out testing accuracy.

In [25]:
scores1 = model.evaluate(x_train,y_train) #training accuracy
scores1

20/20 [==============================] - 0s 4ms/step - loss: 0.0260 - accuracy: 0.9919


[0.026029441505670547, 0.9918566942214966]

In [26]:
scores2 = model.evaluate(x_test,y_test) #testing accuracy
scores2

5/5 [==============================] - 0s 6ms/step - loss: 1.4820 - accuracy: 0.6818


[1.4819600582122803, 0.6818181872367859]

In [27]:
print ("Training accuracy is :",scores1[1] , "and Testing accuracy is :", scores2[1])

Training accuracy is : 0.9918566942214966 and Testing accuracy is : 0.6818181872367859


Since there is a huge difference between both errors/accuracy, we can say that this model is overfitted.

So now we will train model less.

In [29]:
model2 = Sequential()
model2.add(Dense(2, activation = 'relu', input_dim = 8)) #adding input layer
model2.add(Dense(2, activation = 'softmax'))
model2.compile(optimizer='adam', 
             loss = 'categorical_crossentropy',
             metrics = ['accuracy'])
model2.fit(x_train,y_train ,epochs=5)

Epoch 1/5
20/20 [==============================] - 1s 2ms/step - loss: 58.8225 - accuracy: 0.3550
Epoch 2/5
20/20 [==============================] - 0s 3ms/step - loss: 52.2966 - accuracy: 0.3664
Epoch 3/5
20/20 [==============================] - 0s 2ms/step - loss: 46.2269 - accuracy: 0.3795
Epoch 4/5
20/20 [==============================] - 0s 2ms/step - loss: 40.9081 - accuracy: 0.4121
Epoch 5/5
20/20 [==============================] - 0s 2ms/step - loss: 36.2070 - accuracy: 0.4169


In [30]:
scoresa = model2.evaluate(x_train,y_train) #training accuracy
scoresa

20/20 [==============================] - 0s 2ms/step - loss: 33.9848 - accuracy: 0.4218


[33.98481750488281, 0.4218240976333618]

In [31]:
scoresb = model2.evaluate(x_test,y_test) #testing accuracy
scoresb

5/5 [==============================] - 0s 5ms/step - loss: 32.8934 - accuracy: 0.4091


[32.893394470214844, 0.40909090638160706]

In [32]:
print ("Training accuracy is :",scoresa[1] , "and Testing accuracy is :", scoresb[1])

Training accuracy is : 0.4218240976333618 and Testing accuracy is : 0.40909090638160706


Now since errors is high, so here an underfitting problem arises.

### Making Predictions

In [43]:
model.predict([[6,148,72,35,0,33.6,0.627,50]])

1/1 [==============================] - 0s 54ms/step


array([[0.00170073, 0.9982993 ]], dtype=float32)

In [44]:
op = model.predict([[6,148,72,35,0,33.6,0.627,50]])
if op[0][0] >= 0.50:
    print("0")
else:
    print("1")

1/1 [==============================] - 0s 55ms/step
1


In [45]:
op = model2.predict([[6,148,72,35,0,33.6,0.627,50]])
if op[0][0] >= 0.50:
    print("0")
else:
    print("1")

1/1 [==============================] - 0s 115ms/step
1
